package bench

import org.openjdk.jmh.annotations._

class CreationBench {
  @Benchmark def createTuple1         = Tuple1("1")
  @Benchmark def createArrayHList1    : String A_:: ArrayHNil    = ArrayHList1("1")
  @Benchmark def createLinkedHList1   : String L_:: LinkedHNil   = LinkedHList1("1")
  // : Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList1 = Unrolled4HList1("1", Unrolled4HNil)
  @Benchmark def createNullHList1      : String N_:: NullHNil     = new NullHListImpl("1", NullHList.nil).asInstanceOf[String N_:: NullHNil]
  @Benchmark def createTuple2         = Tuple2("1", "2")
  @Benchmark def createArrayHList2    : String A_:: String A_:: ArrayHNil    = ArrayHList2("1", "2")
  @Benchmark def createLinkedHList2   : String L_:: String L_:: LinkedHNil   = LinkedHList2("1", "2")
  // : Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList2 = Unrolled4HList2("1", "2", Unrolled4HNil)
  @Benchmark def createNullHList2      : String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", NullHList.nil).asInstanceOf[String N_:: String N_:: NullHNil]
  @Benchmark def createTuple3         = Tuple3("1", "2", "3")
  @Benchmark def createArrayHList3    : String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList3("1", "2", "3")
  @Benchmark def createLinkedHList3   : String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList3("1", "2", "3")
  // : Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList3 = Unrolled4HList3("1", "2", "3", Unrolled4HNil)
  @Benchmark def createNullHList3      : String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple4         = Tuple4("1", "2", "3", "4")
  @Benchmark def createArrayHList4    : String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList4("1", "2", "3", "4")
  @Benchmark def createLinkedHList4   : String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList4("1", "2", "3", "4")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList4 = Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)
  @Benchmark def createNullHList4      : String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", "4", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple5         = Tuple5("1", "2", "3", "4", "5")
  @Benchmark def createArrayHList5    : String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](5); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; ArrayHListN(a) }
  @Benchmark def createLinkedHList5   : String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList5 = Unrolled4HList1("5", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  @Benchmark def createNullHList5      : String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple6         = Tuple6("1", "2", "3", "4", "5", "6")
  @Benchmark def createArrayHList6    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](6); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; ArrayHListN(a) }
  @Benchmark def createLinkedHList6   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList6 = Unrolled4HList2("5", "6", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  @Benchmark def createNullHList6      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple7         = Tuple7("1", "2", "3", "4", "5", "6", "7")
  @Benchmark def createArrayHList7    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](7); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; ArrayHListN(a) }
  @Benchmark def createLinkedHList7   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList7 = Unrolled4HList3("5", "6", "7", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  @Benchmark def createNullHList7      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple8         = Tuple8("1", "2", "3", "4", "5", "6", "7", "8")
  @Benchmark def createArrayHList8    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](8); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; ArrayHListN(a) }
  @Benchmark def createLinkedHList8   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList8 = Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  @Benchmark def createNullHList8      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple9         = Tuple9("1", "2", "3", "4", "5", "6", "7", "8", "9")
  @Benchmark def createArrayHList9    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](9); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; ArrayHListN(a) }
  @Benchmark def createLinkedHList9   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList9 = Unrolled4HList1("9", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  @Benchmark def createNullHList9      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple10         = Tuple10("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
  @Benchmark def createArrayHList10    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](10); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; ArrayHListN(a) }
  @Benchmark def createLinkedHList10   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList10 = Unrolled4HList2("9", "10", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  @Benchmark def createNullHList10      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple11         = Tuple11("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")
  @Benchmark def createArrayHList11    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](11); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; ArrayHListN(a) }
  @Benchmark def createLinkedHList11   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList11 = Unrolled4HList3("9", "10", "11", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  @Benchmark def createNullHList11      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple12         = Tuple12("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
  @Benchmark def createArrayHList12    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](12); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; ArrayHListN(a) }
  @Benchmark def createLinkedHList12   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList12 = Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  @Benchmark def createNullHList12      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple13         = Tuple13("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13")
  @Benchmark def createArrayHList13    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](13); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; ArrayHListN(a) }
  @Benchmark def createLinkedHList13   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList13 = Unrolled4HList1("13", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  @Benchmark def createNullHList13      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple14         = Tuple14("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14")
  @Benchmark def createArrayHList14    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](14); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; ArrayHListN(a) }
  @Benchmark def createLinkedHList14   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList14 = Unrolled4HList2("13", "14", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  @Benchmark def createNullHList14      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple15         = Tuple15("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15")
  @Benchmark def createArrayHList15    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](15); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; ArrayHListN(a) }
  @Benchmark def createLinkedHList15   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList15 = Unrolled4HList3("13", "14", "15", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  @Benchmark def createNullHList15      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple16         = Tuple16("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16")
  @Benchmark def createArrayHList16    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](16); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; ArrayHListN(a) }
  @Benchmark def createLinkedHList16   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList16 = Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  @Benchmark def createNullHList16      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple17         = Tuple17("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17")
  @Benchmark def createArrayHList17    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](17); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; ArrayHListN(a) }
  @Benchmark def createLinkedHList17   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList17 = Unrolled4HList1("17", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  @Benchmark def createNullHList17      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple18         = Tuple18("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18")
  @Benchmark def createArrayHList18    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](18); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; ArrayHListN(a) }
  @Benchmark def createLinkedHList18   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList18 = Unrolled4HList2("17", "18", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  @Benchmark def createNullHList18      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple19         = Tuple19("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")
  @Benchmark def createArrayHList19    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](19); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; ArrayHListN(a) }
  @Benchmark def createLinkedHList19   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList19 = Unrolled4HList3("17", "18", "19", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  @Benchmark def createNullHList19      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple20         = Tuple20("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20")
  @Benchmark def createArrayHList20    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](20); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; a(19) = "20"; ArrayHListN(a) }
  @Benchmark def createLinkedHList20   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("20", LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList20 = Unrolled4HList4("17", "18", "19", "20", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  @Benchmark def createNullHList20      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createTuple21         = Tuple21("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21")
  @Benchmark def createArrayHList21    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](21); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; a(19) = "20"; a(20) = "21"; ArrayHListN(a) }
  @Benchmark def createLinkedHList21   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("21", LinkedHListN("20", LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  @Benchmark def createUnrolled4HList21 = Unrolled4HList1("21", Unrolled4HList4("17", "18", "19", "20", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))))
  @Benchmark def createNullHList21      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("21", new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
}