package bench

import org.openjdk.jmh.annotations._

class CreationBench {
  @Benchmark def createScalaTuple1    = Tuple1("1")
  @Benchmark def createArrayHList1    = ArrayHList1("1")
  @Benchmark def createLinkedHList1   = LinkedHCons("1", LinkedHNil)
  @Benchmark def createUnrolledHList1 = UnrolledHList1("1", UnrolledHNil)
  @Benchmark def createNullHList1     = new NullHListImpl("1", NullHList.nil)
  @Benchmark def createScalaTuple2    = Tuple2("1", "2")
  @Benchmark def createArrayHList2    = ArrayHList2("1", "2")
  @Benchmark def createLinkedHList2   = LinkedHCons("2", LinkedHCons("1", LinkedHNil))
  @Benchmark def createUnrolledHList2 = UnrolledHList2("1", "2", UnrolledHNil)
  @Benchmark def createNullHList2     = new NullHListImpl("1", "2", NullHList.nil)
  @Benchmark def createScalaTuple3    = Tuple3("1", "2", "3")
  @Benchmark def createArrayHList3    = ArrayHList3("1", "2", "3")
  @Benchmark def createLinkedHList3   = LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil)))
  @Benchmark def createUnrolledHList3 = UnrolledHList3("1", "2", "3", UnrolledHNil)
  @Benchmark def createNullHList3     = new NullHListImpl("1", "2", "3", NullHList.nil)
  @Benchmark def createScalaTuple4    = Tuple4("1", "2", "3", "4")
  @Benchmark def createArrayHList4    = ArrayHList4("1", "2", "3", "4")
  @Benchmark def createLinkedHList4   = LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil))))
  @Benchmark def createUnrolledHList4 = UnrolledHList4("1", "2", "3", "4", UnrolledHNil)
  @Benchmark def createNullHList4     = new NullHListImpl("1", "2", "3", "4", NullHList.nil)
  @Benchmark def createScalaTuple5    = Tuple5("1", "2", "3", "4", "5")
  @Benchmark def createArrayHList5    = ArrayHListN(Array("1", "2", "3", "4", "5"))
  @Benchmark def createLinkedHList5   = LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil)))))
  @Benchmark def createUnrolledHList5 = UnrolledHList1("5", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList5     = new NullHListImpl("5", new NullHListImpl("1", "2", "3", "4", NullHList.nil))
  @Benchmark def createScalaTuple6    = Tuple6("1", "2", "3", "4", "5", "6")
  @Benchmark def createArrayHList6    = ArrayHListN(Array("1", "2", "3", "4", "5", "6"))
  @Benchmark def createLinkedHList6   = LinkedHCons("6", LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil))))))
  @Benchmark def createUnrolledHList6 = UnrolledHList2("5", "6", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList6     = new NullHListImpl("5", "6", new NullHListImpl("1", "2", "3", "4", NullHList.nil))
  @Benchmark def createScalaTuple7    = Tuple7("1", "2", "3", "4", "5", "6", "7")
  @Benchmark def createArrayHList7    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7"))
  @Benchmark def createLinkedHList7   = LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil)))))))
  @Benchmark def createUnrolledHList7 = UnrolledHList3("5", "6", "7", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList7     = new NullHListImpl("5", "6", "7", new NullHListImpl("1", "2", "3", "4", NullHList.nil))
  @Benchmark def createScalaTuple8    = Tuple8("1", "2", "3", "4", "5", "6", "7", "8")
  @Benchmark def createArrayHList8    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8"))
  @Benchmark def createLinkedHList8   = LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil))))))))
  @Benchmark def createUnrolledHList8 = UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList8     = new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))
  @Benchmark def createScalaTuple9    = Tuple9("1", "2", "3", "4", "5", "6", "7", "8", "9")
  @Benchmark def createArrayHList9    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9"))
  @Benchmark def createLinkedHList9   = LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil)))))))))
  @Benchmark def createUnrolledHList9 = UnrolledHList1("9", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList9     = new NullHListImpl("9", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))
  @Benchmark def createScalaTuple10    = Tuple10("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
  @Benchmark def createArrayHList10    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))
  @Benchmark def createLinkedHList10   = LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHCons("4", LinkedHCons("3", LinkedHCons("2", LinkedHCons("1", LinkedHNil))))))))))
  @Benchmark def createUnrolledHList10 = UnrolledHList2("9", "10", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList10     = new NullHListImpl("9", "10", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))
}