package bench

import org.openjdk.jmh.annotations._

class CreationBench {
  @Benchmark def createScalaTuple1         = Tuple1("1")
  @Benchmark def createArrayHList1    : String A_:: ArrayHNil    = ArrayHList1("1")
  @Benchmark def createLinkedHList1   : String L_:: LinkedHNil   = LinkedHList1("1")
  // : Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList1 = UnrolledHList1("1", UnrolledHNil)
  @Benchmark def createNullHList1      : String N_:: NullHNil     = new NullHListImpl("1", NullHList.nil).asInstanceOf[String N_:: NullHNil]
  @Benchmark def createScalaTuple2         = Tuple2("1", "2")
  @Benchmark def createArrayHList2    : String A_:: String A_:: ArrayHNil    = ArrayHList2("1", "2")
  @Benchmark def createLinkedHList2   : String L_:: String L_:: LinkedHNil   = LinkedHList2("1", "2")
  // : Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList2 = UnrolledHList2("1", "2", UnrolledHNil)
  @Benchmark def createNullHList2      : String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", NullHList.nil).asInstanceOf[String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple3         = Tuple3("1", "2", "3")
  @Benchmark def createArrayHList3    : String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList3("1", "2", "3")
  @Benchmark def createLinkedHList3   : String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList3("1", "2", "3")
  // : Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList3 = UnrolledHList3("1", "2", "3", UnrolledHNil)
  @Benchmark def createNullHList3      : String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple4         = Tuple4("1", "2", "3", "4")
  @Benchmark def createArrayHList4    : String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList4("1", "2", "3", "4")
  @Benchmark def createLinkedHList4   : String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList4("1", "2", "3", "4")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList4 = UnrolledHList4("1", "2", "3", "4", UnrolledHNil)
  @Benchmark def createNullHList4      : String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", "4", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple5         = Tuple5("1", "2", "3", "4", "5")
  @Benchmark def createArrayHList5    : String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](5); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; ArrayHListN(a) }
  @Benchmark def createLinkedHList5   : String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList5 = UnrolledHList1("5", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList5      : String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple6         = Tuple6("1", "2", "3", "4", "5", "6")
  @Benchmark def createArrayHList6    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](6); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; ArrayHListN(a) }
  @Benchmark def createLinkedHList6   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList6 = UnrolledHList2("5", "6", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList6      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple7         = Tuple7("1", "2", "3", "4", "5", "6", "7")
  @Benchmark def createArrayHList7    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](7); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; ArrayHListN(a) }
  @Benchmark def createLinkedHList7   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList7 = UnrolledHList3("5", "6", "7", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList7      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple8         = Tuple8("1", "2", "3", "4", "5", "6", "7", "8")
  @Benchmark def createArrayHList8    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](8); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; ArrayHListN(a) }
  @Benchmark def createLinkedHList8   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList8 = UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))
  @Benchmark def createNullHList8      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple9         = Tuple9("1", "2", "3", "4", "5", "6", "7", "8", "9")
  @Benchmark def createArrayHList9    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](9); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; ArrayHListN(a) }
  @Benchmark def createLinkedHList9   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList9 = UnrolledHList1("9", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList9      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple10         = Tuple10("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
  @Benchmark def createArrayHList10    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](10); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; ArrayHListN(a) }
  @Benchmark def createLinkedHList10   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList10 = UnrolledHList2("9", "10", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList10      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple11         = Tuple11("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")
  @Benchmark def createArrayHList11    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](11); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; ArrayHListN(a) }
  @Benchmark def createLinkedHList11   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList11 = UnrolledHList3("9", "10", "11", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList11      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple12         = Tuple12("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
  @Benchmark def createArrayHList12    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](12); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; ArrayHListN(a) }
  @Benchmark def createLinkedHList12   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList12 = UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))
  @Benchmark def createNullHList12      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple13         = Tuple13("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13")
  @Benchmark def createArrayHList13    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](13); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; ArrayHListN(a) }
  @Benchmark def createLinkedHList13   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList13 = UnrolledHList1("13", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))))
  @Benchmark def createNullHList13      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple14         = Tuple14("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14")
  @Benchmark def createArrayHList14    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](14); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; ArrayHListN(a) }
  @Benchmark def createLinkedHList14   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList14 = UnrolledHList2("13", "14", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))))
  @Benchmark def createNullHList14      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple15         = Tuple15("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15")
  @Benchmark def createArrayHList15    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](15); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; ArrayHListN(a) }
  @Benchmark def createLinkedHList15   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList15 = UnrolledHList3("13", "14", "15", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))))
  @Benchmark def createNullHList15      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple16         = Tuple16("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16")
  @Benchmark def createArrayHList16    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](16); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; ArrayHListN(a) }
  @Benchmark def createLinkedHList16   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList16 = UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))))
  @Benchmark def createNullHList16      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple17         = Tuple17("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17")
  @Benchmark def createArrayHList17    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](17); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; ArrayHListN(a) }
  @Benchmark def createLinkedHList17   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList17 = UnrolledHList1("17", UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))))
  @Benchmark def createNullHList17      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple18         = Tuple18("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18")
  @Benchmark def createArrayHList18    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](18); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; ArrayHListN(a) }
  @Benchmark def createLinkedHList18   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList18 = UnrolledHList2("17", "18", UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))))
  @Benchmark def createNullHList18      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple19         = Tuple19("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")
  @Benchmark def createArrayHList19    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](19); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; ArrayHListN(a) }
  @Benchmark def createLinkedHList19   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList19 = UnrolledHList3("17", "18", "19", UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))))
  @Benchmark def createNullHList19      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple20         = Tuple20("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20")
  @Benchmark def createArrayHList20    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](20); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; a(19) = "20"; ArrayHListN(a) }
  @Benchmark def createLinkedHList20   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("20", LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4")))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList20 = UnrolledHList4("17", "18", "19", "20", UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil)))))
  @Benchmark def createNullHList20      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  @Benchmark def createScalaTuple21         = Tuple21("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21")
  @Benchmark def createArrayHList21    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = { val a = new Array[Any](21); a(0) = "1"; a(1) = "2"; a(2) = "3"; a(3) = "4"; a(4) = "5"; a(5) = "6"; a(6) = "7"; a(7) = "8"; a(8) = "9"; a(9) = "10"; a(10) = "11"; a(11) = "12"; a(12) = "13"; a(13) = "14"; a(14) = "15"; a(15) = "16"; a(16) = "17"; a(17) = "18"; a(18) = "19"; a(19) = "20"; a(20) = "21"; ArrayHListN(a) }
  @Benchmark def createLinkedHList21   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHListN("21", LinkedHListN("20", LinkedHListN("19", LinkedHListN("18", LinkedHListN("17", LinkedHListN("16", LinkedHListN("15", LinkedHListN("14", LinkedHListN("13", LinkedHListN("12", LinkedHListN("11", LinkedHListN("10", LinkedHListN("9", LinkedHListN("8", LinkedHListN("7", LinkedHListN("6", LinkedHListN("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))))
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: UnrolledHNil
  @Benchmark def createUnrolledHList21 = UnrolledHList1("21", UnrolledHList4("17", "18", "19", "20", UnrolledHList4("13", "14", "15", "16", UnrolledHList4("9", "10", "11", "12", UnrolledHList4("5", "6", "7", "8", UnrolledHList4("1", "2", "3", "4", UnrolledHNil))))))
  @Benchmark def createNullHList21      : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("21", new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
}
