package bench

import org.openjdk.jmh.annotations._

@State(Scope.Thread)
object DataDef {
  val tuple1         = Tuple1("1")
  // : Int U4_:: Unrolled4HNil
  val unrolledHList1 = Unrolled4HList1("1", Unrolled4HNil)
  val arrayHList1    : String A_:: ArrayHNil    = ArrayHList1("1")
  val linkedHList1   : String L_:: LinkedHNil   = LinkedHList1("1")
  val nullHList1     : String N_:: NullHNil     = new NullHListImpl("1", NullHList.nil).asInstanceOf[String N_:: NullHNil]
  val tuple2         = Tuple2("1", "2")
  // : Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList2 = Unrolled4HList2("1", "2", Unrolled4HNil)
  val arrayHList2    : String A_:: String A_:: ArrayHNil    = ArrayHList2("1", "2")
  val linkedHList2   : String L_:: String L_:: LinkedHNil   = LinkedHList2("1", "2")
  val nullHList2     : String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", NullHList.nil).asInstanceOf[String N_:: String N_:: NullHNil]
  val tuple3         = Tuple3("1", "2", "3")
  // : Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList3 = Unrolled4HList3("1", "2", "3", Unrolled4HNil)
  val arrayHList3    : String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList3("1", "2", "3")
  val linkedHList3   : String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList3("1", "2", "3")
  val nullHList3     : String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: NullHNil]
  val tuple4         = Tuple4("1", "2", "3", "4")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList4 = Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)
  val arrayHList4    : String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHList4("1", "2", "3", "4")
  val linkedHList4   : String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHList4("1", "2", "3", "4")
  val nullHList4     : String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("1", "2", "3", "4", NullHList.nil).asInstanceOf[String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple5         = Tuple5("1", "2", "3", "4", "5")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList5 = Unrolled4HList1("5", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  val arrayHList5    : String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5"))
  val linkedHList5   : String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))
  val nullHList5     : String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple6         = Tuple6("1", "2", "3", "4", "5", "6")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList6 = Unrolled4HList2("5", "6", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  val arrayHList6    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6"))
  val linkedHList6   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))
  val nullHList6     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple7         = Tuple7("1", "2", "3", "4", "5", "6", "7")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList7 = Unrolled4HList3("5", "6", "7", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  val arrayHList7    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7"))
  val linkedHList7   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))
  val nullHList7     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple8         = Tuple8("1", "2", "3", "4", "5", "6", "7", "8")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList8 = Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))
  val arrayHList8    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8"))
  val linkedHList8   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))
  val nullHList8     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple9         = Tuple9("1", "2", "3", "4", "5", "6", "7", "8", "9")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList9 = Unrolled4HList1("9", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  val arrayHList9    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9"))
  val linkedHList9   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))
  val nullHList9     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple10         = Tuple10("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList10 = Unrolled4HList2("9", "10", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  val arrayHList10    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))
  val linkedHList10   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))
  val nullHList10     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple11         = Tuple11("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList11 = Unrolled4HList3("9", "10", "11", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  val arrayHList11    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"))
  val linkedHList11   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))
  val nullHList11     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple12         = Tuple12("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList12 = Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))
  val arrayHList12    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"))
  val linkedHList12   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))))
  val nullHList12     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple13         = Tuple13("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList13 = Unrolled4HList1("13", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  val arrayHList13    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"))
  val linkedHList13   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))))
  val nullHList13     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple14         = Tuple14("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList14 = Unrolled4HList2("13", "14", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  val arrayHList14    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"))
  val linkedHList14   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))))))
  val nullHList14     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple15         = Tuple15("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList15 = Unrolled4HList3("13", "14", "15", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  val arrayHList15    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"))
  val linkedHList15   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))))))
  val nullHList15     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple16         = Tuple16("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList16 = Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))
  val arrayHList16    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"))
  val linkedHList16   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))))))))
  val nullHList16     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple17         = Tuple17("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList17 = Unrolled4HList1("17", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  val arrayHList17    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"))
  val linkedHList17   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("17", LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))))))))
  val nullHList17     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple18         = Tuple18("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList18 = Unrolled4HList2("17", "18", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  val arrayHList18    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"))
  val linkedHList18   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("18", LinkedHCons("17", LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))))))))))
  val nullHList18     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple19         = Tuple19("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList19 = Unrolled4HList3("17", "18", "19", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  val arrayHList19    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"))
  val linkedHList19   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("19", LinkedHCons("18", LinkedHCons("17", LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))
  val nullHList19     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple20         = Tuple20("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList20 = Unrolled4HList4("17", "18", "19", "20", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil)))))
  val arrayHList20    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"))
  val linkedHList20   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("20", LinkedHCons("19", LinkedHCons("18", LinkedHCons("17", LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4")))))))))))))))))
  val nullHList20     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
  val tuple21         = Tuple21("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21")
  // : Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Int U4_:: Unrolled4HNil
  val unrolledHList21 = Unrolled4HList1("21", Unrolled4HList4("17", "18", "19", "20", Unrolled4HList4("13", "14", "15", "16", Unrolled4HList4("9", "10", "11", "12", Unrolled4HList4("5", "6", "7", "8", Unrolled4HList4("1", "2", "3", "4", Unrolled4HNil))))))
  val arrayHList21    : String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: String A_:: ArrayHNil    = ArrayHListN(Array("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"))
  val linkedHList21   : String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: String L_:: LinkedHNil   = LinkedHCons("21", LinkedHCons("20", LinkedHCons("19", LinkedHCons("18", LinkedHCons("17", LinkedHCons("16", LinkedHCons("15", LinkedHCons("14", LinkedHCons("13", LinkedHCons("12", LinkedHCons("11", LinkedHCons("10", LinkedHCons("9", LinkedHCons("8", LinkedHCons("7", LinkedHCons("6", LinkedHCons("5", LinkedHList4("1", "2", "3", "4"))))))))))))))))))
  val nullHList21     : String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil     = new NullHListImpl("21", new NullHListImpl("17", "18", "19", "20", new NullHListImpl("13", "14", "15", "16", new NullHListImpl("9", "10", "11", "12", new NullHListImpl("5", "6", "7", "8", new NullHListImpl("1", "2", "3", "4", NullHList.nil)))))).asInstanceOf[String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: String N_:: NullHNil]
}